-- Run once in the Supabase SQL Editor before starting the app.
-- Private schema: intentionally outside the default public Data API schema.
CREATE SCHEMA IF NOT EXISTS qc_portal;
REVOKE ALL ON SCHEMA qc_portal FROM PUBLIC;

CREATE TABLE IF NOT EXISTS qc_portal.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    email TEXT NOT NULL DEFAULT '',
    test_date DATE,
    invitation_sent_at TIMESTAMPTZ,
    password TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('Candidate', 'Reviewer', 'Admin'))
);
CREATE TABLE IF NOT EXISTS qc_portal.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discipline TEXT NOT NULL,
    q_type TEXT NOT NULL CHECK (q_type IN ('mcq', 'essay', 'practicum', 'oral', 'practical')),
    question_text TEXT NOT NULL,
    options TEXT,
    correct_answer TEXT,
    rubric TEXT,
    max_points INTEGER NOT NULL CHECK (max_points > 0),
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1))
);
CREATE TABLE IF NOT EXISTS qc_portal.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_name TEXT NOT NULL,
    designation TEXT NOT NULL DEFAULT '',
    iqama_no TEXT NOT NULL DEFAULT '',
    employee_no TEXT NOT NULL DEFAULT '',
    exam_date DATE NOT NULL DEFAULT CURRENT_DATE,
    project_location TEXT NOT NULL DEFAULT '',
    discipline TEXT NOT NULL,
    mcq_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    essay_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    max_possible_points DOUBLE PRECISION NOT NULL CHECK (max_possible_points > 0),
    status TEXT NOT NULL CHECK (status IN ('Pending Review', 'Graded')),
    reviewer_comments TEXT DEFAULT '',
    user_id BIGINT REFERENCES qc_portal.users(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    graded_at TIMESTAMPTZ,
    reviewer_id BIGINT REFERENCES qc_portal.users(id),
    token TEXT UNIQUE
);
CREATE TABLE IF NOT EXISTS qc_portal.answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL REFERENCES qc_portal.submissions(id),
    question_id BIGINT NOT NULL REFERENCES qc_portal.questions(id),
    submitted_answer TEXT NOT NULL,
    awarded_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    snapshot TEXT NOT NULL,
    UNIQUE (submission_id, question_id)
);
CREATE INDEX IF NOT EXISTS submissions_user_idx ON qc_portal.submissions(user_id);
CREATE INDEX IF NOT EXISTS answers_submission_idx ON qc_portal.answers(submission_id);
CREATE INDEX IF NOT EXISTS questions_discipline_idx ON qc_portal.questions(discipline);

-- No client API policies: only the trusted server's database owner connection
-- accesses these tables. App-level roles are checked in database.py.
ALTER TABLE qc_portal.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_portal.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_portal.submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_portal.answers ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA qc_portal FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA qc_portal FROM PUBLIC;
